/*
 * ExaVault API
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//*


package com.exavault.client.api;

import com.exavault.client.ApiException;
import com.exavault.client.model.AccountResponse;
import com.exavault.client.model.UpdateAccountRequestBody;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

*/
/**
 * API tests for AccountApi
 * Get account settings
 * Get setttings for your account, such as current space usage, webhooks settings, welcome email content and IP address restrictions.
 *//*

@Ignore
public class AccountApiTest {

    private final AccountApi api = new AccountApi();

    */
/**
 * Get account settings
 *
 * Get setttings for your account, such as current space usage, webhooks settings, welcome email content and IP address restrictions.
 *
 * @throws ApiException
 *          if the Api call fails
 *//*

    @Test
    public void getAccountTest() throws ApiException {
        String evApiKey = null;
        String evAccessToken = null;
        String include = null;
        AccountResponse response = api.getAccount(evApiKey, evAccessToken, include);

        // TODO: test validations
    }
    */
/**
 * Update account settings
 *
 * Update account settings, such as welcome email content, IP address restrictions, webhooks settings and secure password requirements.  **Notes**  - You must have [admin-level access](/docs/account/04-users/00-introduction#managing-user-roles-and-permissions) to change account settings.
 *
 * @throws ApiException
 *          if the Api call fails
 *//*

    @Test
    public void updateAccountTest() throws ApiException {
        String evApiKey = null;
        String evAccessToken = null;
        UpdateAccountRequestBody body = null;
        AccountResponse response = api.updateAccount(evApiKey, evAccessToken, body);

        // TODO: test validations
    }
}
*/
