/*
 * ExaVault API
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.exavault.client.api;

import com.exavault.client.ApiException;
import com.exavault.client.model.EmptyResponse;
import com.exavault.client.model.SendReferralEmailRequestBody;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EmailApi
 */
@Ignore
public class EmailApiTest {

    private final EmailApi api = new EmailApi();

    /**
     * Send referral email to a given address
     *
     * Invite a friend to sign up for a free trial of ExaVault. Send a [referral](/lp/referafriend/) email to an email address. If the recipient signs up for ExaVault, we&#x27;ll apply a credit to your account for the referral. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendReferralEmailTest() throws ApiException {
        String evApiKey = null;
        String evAccessToken = null;
        SendReferralEmailRequestBody body = null;
        EmptyResponse response = api.sendReferralEmail(evApiKey, evAccessToken, body);

        // TODO: test validations
    }
    /**
     * Resend welcome email to specific user
     *
     * Send a welcome email to a user. The contents of the welcome email can be set by [PATCH /accounts](#operation/updateAccount).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendWelcomeEmailTest() throws ApiException {
        String evApiKey = null;
        String evAccessToken = null;
        String username = null;
        EmptyResponse response = api.sendWelcomeEmail(evApiKey, evAccessToken, username);

        // TODO: test validations
    }
}
