/*
 * ExaVault API
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.exavault.client.api;

import com.exavault.client.ApiException;
import com.exavault.client.model.ResendInvitationsRequestBody;
import com.exavault.client.model.ShareRecipientsResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RecipientsApi
 */
@Ignore
public class RecipientsApiTest {

    private final RecipientsApi api = new RecipientsApi();

    /**
     * Resend invitations to share recipients
     *
     * Resend invitations to one or all recipients attached to specified share. The most recent message that was sent for the share will be re-used for this email.  You can use [GET /shares/{id}](#operation/getShareById) to view the recipient list and message history for a share. Use [PATCH /shares/{id}](#operation/updateShareById) to add or remove recipients.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void resendInvitationsForShareTest() throws ApiException {
        String evApiKey = null;
        String evAccessToken = null;
        Integer shareId = null;
        ResendInvitationsRequestBody body = null;
        ShareRecipientsResponse response = api.resendInvitationsForShare(evApiKey, evAccessToken, shareId, body);

        // TODO: test validations
    }
}
