/*
 * ExaVault API
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.exavault.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * AddEmailListRequestBody
 */


public class AddEmailListRequestBody {
  @SerializedName("name")
  private String name = null;

  @SerializedName("emails")
  private List<String> emails = new ArrayList<String>();

  public AddEmailListRequestBody name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the email list. 
   * @return name
  **/
  @Schema(example = "My friends list", required = true, description = "Name of the email list. ")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AddEmailListRequestBody emails(List<String> emails) {
    this.emails = emails;
    return this;
  }

  public AddEmailListRequestBody addEmailsItem(String emailsItem) {
    this.emails.add(emailsItem);
    return this;
  }

   /**
   * Array of email addresses to include in the email list. 
   * @return emails
  **/
  @Schema(example = "[\"johns@example.com\",\"jdoe@example.com\"]", required = true, description = "Array of email addresses to include in the email list. ")
  public List<String> getEmails() {
    return emails;
  }

  public void setEmails(List<String> emails) {
    this.emails = emails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddEmailListRequestBody addEmailListRequestBody = (AddEmailListRequestBody) o;
    return Objects.equals(this.name, addEmailListRequestBody.name) &&
        Objects.equals(this.emails, addEmailListRequestBody.emails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, emails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddEmailListRequestBody {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    emails: ").append(toIndentedString(emails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
