/*
 * ExaVault API
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.exavault.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * AddFolderRequestBody
 */


public class AddFolderRequestBody {
  @SerializedName("path")
  private String path = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("parentResource")
  private String parentResource = null;

  public AddFolderRequestBody path(String path) {
    this.path = path;
    return this;
  }

   /**
   * Fully-qualified path to the new folder including folder&#x27;s name
   * @return path
  **/
  @Schema(description = "Fully-qualified path to the new folder including folder's name")
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }

  public AddFolderRequestBody name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the folder to create. Required if **path** is not used
   * @return name
  **/
  @Schema(description = "Name of the folder to create. Required if **path** is not used")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AddFolderRequestBody parentResource(String parentResource) {
    this.parentResource = parentResource;
    return this;
  }

   /**
   * Resource identifier where to create a folder. Required if **path** is not used
   * @return parentResource
  **/
  @Schema(description = "Resource identifier where to create a folder. Required if **path** is not used")
  public String getParentResource() {
    return parentResource;
  }

  public void setParentResource(String parentResource) {
    this.parentResource = parentResource;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddFolderRequestBody addFolderRequestBody = (AddFolderRequestBody) o;
    return Objects.equals(this.path, addFolderRequestBody.path) &&
        Objects.equals(this.name, addFolderRequestBody.name) &&
        Objects.equals(this.parentResource, addFolderRequestBody.parentResource);
  }

  @Override
  public int hashCode() {
    return Objects.hash(path, name, parentResource);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddFolderRequestBody {\n");
    
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    parentResource: ").append(toIndentedString(parentResource)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
