/*
 * ExaVault API
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.exavault.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * BrandingSettingsValues
 */


public class BrandingSettingsValues {
  @SerializedName("companyName")
  private String companyName = null;

  @SerializedName("customEmail")
  private String customEmail = null;

  @SerializedName("theme")
  private String theme = null;

  public BrandingSettingsValues companyName(String companyName) {
    this.companyName = companyName;
    return this;
  }

   /**
   * Custom company name to include in copyright and title bar.
   * @return companyName
  **/
  @Schema(description = "Custom company name to include in copyright and title bar.")
  public String getCompanyName() {
    return companyName;
  }

  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }

  public BrandingSettingsValues customEmail(String customEmail) {
    this.customEmail = customEmail;
    return this;
  }

   /**
   * Address to use as sender of email messages generated by ExaVault
   * @return customEmail
  **/
  @Schema(example = "custom@example.com", description = "Address to use as sender of email messages generated by ExaVault")
  public String getCustomEmail() {
    return customEmail;
  }

  public void setCustomEmail(String customEmail) {
    this.customEmail = customEmail;
  }

  public BrandingSettingsValues theme(String theme) {
    this.theme = theme;
    return this;
  }

   /**
   * Color scheme for web file manager. Valid options are **default**, **light** and **dark**
   * @return theme
  **/
  @Schema(example = "default", description = "Color scheme for web file manager. Valid options are **default**, **light** and **dark**")
  public String getTheme() {
    return theme;
  }

  public void setTheme(String theme) {
    this.theme = theme;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BrandingSettingsValues brandingSettingsValues = (BrandingSettingsValues) o;
    return Objects.equals(this.companyName, brandingSettingsValues.companyName) &&
        Objects.equals(this.customEmail, brandingSettingsValues.customEmail) &&
        Objects.equals(this.theme, brandingSettingsValues.theme);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyName, customEmail, theme);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BrandingSettingsValues {\n");
    
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    customEmail: ").append(toIndentedString(customEmail)).append("\n");
    sb.append("    theme: ").append(toIndentedString(theme)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
