/*
 * ExaVault API
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.exavault.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CallbackSettingsTriggers
 */


public class CallbackSettingsTriggers {
  @SerializedName("upload")
  private Boolean upload = null;

  @SerializedName("download")
  private Boolean download = null;

  @SerializedName("delete")
  private Boolean delete = null;

  @SerializedName("createFolder")
  private Boolean createFolder = null;

  @SerializedName("rename")
  private Boolean rename = null;

  @SerializedName("move")
  private Boolean move = null;

  @SerializedName("copy")
  private Boolean copy = null;

  @SerializedName("compress")
  private Boolean compress = null;

  @SerializedName("extract")
  private Boolean extract = null;

  @SerializedName("shareFolder")
  private Boolean shareFolder = null;

  @SerializedName("sendFiles")
  private Boolean sendFiles = null;

  @SerializedName("receiveFiles")
  private Boolean receiveFiles = null;

  @SerializedName("updateShare")
  private Boolean updateShare = null;

  @SerializedName("updateReceive")
  private Boolean updateReceive = null;

  @SerializedName("deleteSend")
  private Boolean deleteSend = null;

  @SerializedName("deleteReceive")
  private Boolean deleteReceive = null;

  @SerializedName("deleteShare")
  private Boolean deleteShare = null;

  @SerializedName("createNotification")
  private Boolean createNotification = null;

  @SerializedName("updateNotification")
  private Boolean updateNotification = null;

  @SerializedName("deleteNotification")
  private Boolean deleteNotification = null;

  @SerializedName("createUser")
  private Boolean createUser = null;

  @SerializedName("updateUser")
  private Boolean updateUser = null;

  @SerializedName("deleteUser")
  private Boolean deleteUser = null;

  @SerializedName("userConnect")
  private Boolean userConnect = null;

  @SerializedName("userDisconnect")
  private Boolean userDisconnect = null;

  public CallbackSettingsTriggers upload(Boolean upload) {
    this.upload = upload;
    return this;
  }

   /**
   * Trigger callback on upload.
   * @return upload
  **/
  @Schema(example = "true", description = "Trigger callback on upload.")
  public Boolean isUpload() {
    return upload;
  }

  public void setUpload(Boolean upload) {
    this.upload = upload;
  }

  public CallbackSettingsTriggers download(Boolean download) {
    this.download = download;
    return this;
  }

   /**
   * Trigger callback on download.
   * @return download
  **/
  @Schema(example = "false", description = "Trigger callback on download.")
  public Boolean isDownload() {
    return download;
  }

  public void setDownload(Boolean download) {
    this.download = download;
  }

  public CallbackSettingsTriggers delete(Boolean delete) {
    this.delete = delete;
    return this;
  }

   /**
   * Trigger callback on delete.
   * @return delete
  **/
  @Schema(example = "false", description = "Trigger callback on delete.")
  public Boolean isDelete() {
    return delete;
  }

  public void setDelete(Boolean delete) {
    this.delete = delete;
  }

  public CallbackSettingsTriggers createFolder(Boolean createFolder) {
    this.createFolder = createFolder;
    return this;
  }

   /**
   * Trigger callback on fodler create.
   * @return createFolder
  **/
  @Schema(example = "true", description = "Trigger callback on fodler create.")
  public Boolean isCreateFolder() {
    return createFolder;
  }

  public void setCreateFolder(Boolean createFolder) {
    this.createFolder = createFolder;
  }

  public CallbackSettingsTriggers rename(Boolean rename) {
    this.rename = rename;
    return this;
  }

   /**
   * Trigger callback on rename.
   * @return rename
  **/
  @Schema(example = "false", description = "Trigger callback on rename.")
  public Boolean isRename() {
    return rename;
  }

  public void setRename(Boolean rename) {
    this.rename = rename;
  }

  public CallbackSettingsTriggers move(Boolean move) {
    this.move = move;
    return this;
  }

   /**
   * Trigger callback on move.
   * @return move
  **/
  @Schema(example = "false", description = "Trigger callback on move.")
  public Boolean isMove() {
    return move;
  }

  public void setMove(Boolean move) {
    this.move = move;
  }

  public CallbackSettingsTriggers copy(Boolean copy) {
    this.copy = copy;
    return this;
  }

   /**
   * Trigger callback on copy.
   * @return copy
  **/
  @Schema(example = "false", description = "Trigger callback on copy.")
  public Boolean isCopy() {
    return copy;
  }

  public void setCopy(Boolean copy) {
    this.copy = copy;
  }

  public CallbackSettingsTriggers compress(Boolean compress) {
    this.compress = compress;
    return this;
  }

   /**
   * Trigger callback on compress.
   * @return compress
  **/
  @Schema(example = "false", description = "Trigger callback on compress.")
  public Boolean isCompress() {
    return compress;
  }

  public void setCompress(Boolean compress) {
    this.compress = compress;
  }

  public CallbackSettingsTriggers extract(Boolean extract) {
    this.extract = extract;
    return this;
  }

   /**
   * Trigger callback on extract.
   * @return extract
  **/
  @Schema(example = "false", description = "Trigger callback on extract.")
  public Boolean isExtract() {
    return extract;
  }

  public void setExtract(Boolean extract) {
    this.extract = extract;
  }

  public CallbackSettingsTriggers shareFolder(Boolean shareFolder) {
    this.shareFolder = shareFolder;
    return this;
  }

   /**
   * Trigger callback on share folder create.
   * @return shareFolder
  **/
  @Schema(example = "false", description = "Trigger callback on share folder create.")
  public Boolean isShareFolder() {
    return shareFolder;
  }

  public void setShareFolder(Boolean shareFolder) {
    this.shareFolder = shareFolder;
  }

  public CallbackSettingsTriggers sendFiles(Boolean sendFiles) {
    this.sendFiles = sendFiles;
    return this;
  }

   /**
   * Trigger callback on send files.
   * @return sendFiles
  **/
  @Schema(example = "false", description = "Trigger callback on send files.")
  public Boolean isSendFiles() {
    return sendFiles;
  }

  public void setSendFiles(Boolean sendFiles) {
    this.sendFiles = sendFiles;
  }

  public CallbackSettingsTriggers receiveFiles(Boolean receiveFiles) {
    this.receiveFiles = receiveFiles;
    return this;
  }

   /**
   * Trigger callback on receive folder create.
   * @return receiveFiles
  **/
  @Schema(example = "false", description = "Trigger callback on receive folder create.")
  public Boolean isReceiveFiles() {
    return receiveFiles;
  }

  public void setReceiveFiles(Boolean receiveFiles) {
    this.receiveFiles = receiveFiles;
  }

  public CallbackSettingsTriggers updateShare(Boolean updateShare) {
    this.updateShare = updateShare;
    return this;
  }

   /**
   * Trigger callback on share folder update.
   * @return updateShare
  **/
  @Schema(example = "false", description = "Trigger callback on share folder update.")
  public Boolean isUpdateShare() {
    return updateShare;
  }

  public void setUpdateShare(Boolean updateShare) {
    this.updateShare = updateShare;
  }

  public CallbackSettingsTriggers updateReceive(Boolean updateReceive) {
    this.updateReceive = updateReceive;
    return this;
  }

   /**
   * Trigger callback on receive folder update.
   * @return updateReceive
  **/
  @Schema(example = "false", description = "Trigger callback on receive folder update.")
  public Boolean isUpdateReceive() {
    return updateReceive;
  }

  public void setUpdateReceive(Boolean updateReceive) {
    this.updateReceive = updateReceive;
  }

  public CallbackSettingsTriggers deleteSend(Boolean deleteSend) {
    this.deleteSend = deleteSend;
    return this;
  }

   /**
   * Trigger callback on send files delete.
   * @return deleteSend
  **/
  @Schema(example = "false", description = "Trigger callback on send files delete.")
  public Boolean isDeleteSend() {
    return deleteSend;
  }

  public void setDeleteSend(Boolean deleteSend) {
    this.deleteSend = deleteSend;
  }

  public CallbackSettingsTriggers deleteReceive(Boolean deleteReceive) {
    this.deleteReceive = deleteReceive;
    return this;
  }

   /**
   * Trigger callback on receive folder delete.
   * @return deleteReceive
  **/
  @Schema(example = "false", description = "Trigger callback on receive folder delete.")
  public Boolean isDeleteReceive() {
    return deleteReceive;
  }

  public void setDeleteReceive(Boolean deleteReceive) {
    this.deleteReceive = deleteReceive;
  }

  public CallbackSettingsTriggers deleteShare(Boolean deleteShare) {
    this.deleteShare = deleteShare;
    return this;
  }

   /**
   * Trigger callback on share folder delete.
   * @return deleteShare
  **/
  @Schema(example = "false", description = "Trigger callback on share folder delete.")
  public Boolean isDeleteShare() {
    return deleteShare;
  }

  public void setDeleteShare(Boolean deleteShare) {
    this.deleteShare = deleteShare;
  }

  public CallbackSettingsTriggers createNotification(Boolean createNotification) {
    this.createNotification = createNotification;
    return this;
  }

   /**
   * Trigger callback on notification create.
   * @return createNotification
  **/
  @Schema(example = "false", description = "Trigger callback on notification create.")
  public Boolean isCreateNotification() {
    return createNotification;
  }

  public void setCreateNotification(Boolean createNotification) {
    this.createNotification = createNotification;
  }

  public CallbackSettingsTriggers updateNotification(Boolean updateNotification) {
    this.updateNotification = updateNotification;
    return this;
  }

   /**
   * Trigger callback on notification update.
   * @return updateNotification
  **/
  @Schema(example = "true", description = "Trigger callback on notification update.")
  public Boolean isUpdateNotification() {
    return updateNotification;
  }

  public void setUpdateNotification(Boolean updateNotification) {
    this.updateNotification = updateNotification;
  }

  public CallbackSettingsTriggers deleteNotification(Boolean deleteNotification) {
    this.deleteNotification = deleteNotification;
    return this;
  }

   /**
   * Trigger callback on notification delete.
   * @return deleteNotification
  **/
  @Schema(example = "false", description = "Trigger callback on notification delete.")
  public Boolean isDeleteNotification() {
    return deleteNotification;
  }

  public void setDeleteNotification(Boolean deleteNotification) {
    this.deleteNotification = deleteNotification;
  }

  public CallbackSettingsTriggers createUser(Boolean createUser) {
    this.createUser = createUser;
    return this;
  }

   /**
   * Trigger callback on user create.
   * @return createUser
  **/
  @Schema(example = "false", description = "Trigger callback on user create.")
  public Boolean isCreateUser() {
    return createUser;
  }

  public void setCreateUser(Boolean createUser) {
    this.createUser = createUser;
  }

  public CallbackSettingsTriggers updateUser(Boolean updateUser) {
    this.updateUser = updateUser;
    return this;
  }

   /**
   * Trigger callback on user update.
   * @return updateUser
  **/
  @Schema(example = "false", description = "Trigger callback on user update.")
  public Boolean isUpdateUser() {
    return updateUser;
  }

  public void setUpdateUser(Boolean updateUser) {
    this.updateUser = updateUser;
  }

  public CallbackSettingsTriggers deleteUser(Boolean deleteUser) {
    this.deleteUser = deleteUser;
    return this;
  }

   /**
   * Trigger callback on user delete.
   * @return deleteUser
  **/
  @Schema(example = "false", description = "Trigger callback on user delete.")
  public Boolean isDeleteUser() {
    return deleteUser;
  }

  public void setDeleteUser(Boolean deleteUser) {
    this.deleteUser = deleteUser;
  }

  public CallbackSettingsTriggers userConnect(Boolean userConnect) {
    this.userConnect = userConnect;
    return this;
  }

   /**
   * Trigger callback on user connect.
   * @return userConnect
  **/
  @Schema(example = "false", description = "Trigger callback on user connect.")
  public Boolean isUserConnect() {
    return userConnect;
  }

  public void setUserConnect(Boolean userConnect) {
    this.userConnect = userConnect;
  }

  public CallbackSettingsTriggers userDisconnect(Boolean userDisconnect) {
    this.userDisconnect = userDisconnect;
    return this;
  }

   /**
   * Trigger callback on user disconnect.
   * @return userDisconnect
  **/
  @Schema(example = "false", description = "Trigger callback on user disconnect.")
  public Boolean isUserDisconnect() {
    return userDisconnect;
  }

  public void setUserDisconnect(Boolean userDisconnect) {
    this.userDisconnect = userDisconnect;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CallbackSettingsTriggers callbackSettingsTriggers = (CallbackSettingsTriggers) o;
    return Objects.equals(this.upload, callbackSettingsTriggers.upload) &&
        Objects.equals(this.download, callbackSettingsTriggers.download) &&
        Objects.equals(this.delete, callbackSettingsTriggers.delete) &&
        Objects.equals(this.createFolder, callbackSettingsTriggers.createFolder) &&
        Objects.equals(this.rename, callbackSettingsTriggers.rename) &&
        Objects.equals(this.move, callbackSettingsTriggers.move) &&
        Objects.equals(this.copy, callbackSettingsTriggers.copy) &&
        Objects.equals(this.compress, callbackSettingsTriggers.compress) &&
        Objects.equals(this.extract, callbackSettingsTriggers.extract) &&
        Objects.equals(this.shareFolder, callbackSettingsTriggers.shareFolder) &&
        Objects.equals(this.sendFiles, callbackSettingsTriggers.sendFiles) &&
        Objects.equals(this.receiveFiles, callbackSettingsTriggers.receiveFiles) &&
        Objects.equals(this.updateShare, callbackSettingsTriggers.updateShare) &&
        Objects.equals(this.updateReceive, callbackSettingsTriggers.updateReceive) &&
        Objects.equals(this.deleteSend, callbackSettingsTriggers.deleteSend) &&
        Objects.equals(this.deleteReceive, callbackSettingsTriggers.deleteReceive) &&
        Objects.equals(this.deleteShare, callbackSettingsTriggers.deleteShare) &&
        Objects.equals(this.createNotification, callbackSettingsTriggers.createNotification) &&
        Objects.equals(this.updateNotification, callbackSettingsTriggers.updateNotification) &&
        Objects.equals(this.deleteNotification, callbackSettingsTriggers.deleteNotification) &&
        Objects.equals(this.createUser, callbackSettingsTriggers.createUser) &&
        Objects.equals(this.updateUser, callbackSettingsTriggers.updateUser) &&
        Objects.equals(this.deleteUser, callbackSettingsTriggers.deleteUser) &&
        Objects.equals(this.userConnect, callbackSettingsTriggers.userConnect) &&
        Objects.equals(this.userDisconnect, callbackSettingsTriggers.userDisconnect);
  }

  @Override
  public int hashCode() {
    return Objects.hash(upload, download, delete, createFolder, rename, move, copy, compress, extract, shareFolder, sendFiles, receiveFiles, updateShare, updateReceive, deleteSend, deleteReceive, deleteShare, createNotification, updateNotification, deleteNotification, createUser, updateUser, deleteUser, userConnect, userDisconnect);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CallbackSettingsTriggers {\n");
    
    sb.append("    upload: ").append(toIndentedString(upload)).append("\n");
    sb.append("    download: ").append(toIndentedString(download)).append("\n");
    sb.append("    delete: ").append(toIndentedString(delete)).append("\n");
    sb.append("    createFolder: ").append(toIndentedString(createFolder)).append("\n");
    sb.append("    rename: ").append(toIndentedString(rename)).append("\n");
    sb.append("    move: ").append(toIndentedString(move)).append("\n");
    sb.append("    copy: ").append(toIndentedString(copy)).append("\n");
    sb.append("    compress: ").append(toIndentedString(compress)).append("\n");
    sb.append("    extract: ").append(toIndentedString(extract)).append("\n");
    sb.append("    shareFolder: ").append(toIndentedString(shareFolder)).append("\n");
    sb.append("    sendFiles: ").append(toIndentedString(sendFiles)).append("\n");
    sb.append("    receiveFiles: ").append(toIndentedString(receiveFiles)).append("\n");
    sb.append("    updateShare: ").append(toIndentedString(updateShare)).append("\n");
    sb.append("    updateReceive: ").append(toIndentedString(updateReceive)).append("\n");
    sb.append("    deleteSend: ").append(toIndentedString(deleteSend)).append("\n");
    sb.append("    deleteReceive: ").append(toIndentedString(deleteReceive)).append("\n");
    sb.append("    deleteShare: ").append(toIndentedString(deleteShare)).append("\n");
    sb.append("    createNotification: ").append(toIndentedString(createNotification)).append("\n");
    sb.append("    updateNotification: ").append(toIndentedString(updateNotification)).append("\n");
    sb.append("    deleteNotification: ").append(toIndentedString(deleteNotification)).append("\n");
    sb.append("    createUser: ").append(toIndentedString(createUser)).append("\n");
    sb.append("    updateUser: ").append(toIndentedString(updateUser)).append("\n");
    sb.append("    deleteUser: ").append(toIndentedString(deleteUser)).append("\n");
    sb.append("    userConnect: ").append(toIndentedString(userConnect)).append("\n");
    sb.append("    userDisconnect: ").append(toIndentedString(userDisconnect)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
