/*
 * ExaVault API
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.exavault.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Object contains infromation about ongoing arhivation of files for download.
 */
@Schema(description = "Object contains infromation about ongoing arhivation of files for download.")

public class DownloadPolling {
  @SerializedName("pollingArchiveName")
  private String pollingArchiveName = null;

  @SerializedName("percent")
  private Integer percent = null;

  public DownloadPolling pollingArchiveName(String pollingArchiveName) {
    this.pollingArchiveName = pollingArchiveName;
    return this;
  }

   /**
   * Name of the zip file.
   * @return pollingArchiveName
  **/
  @Schema(example = "/zipname.zip", description = "Name of the zip file.")
  public String getPollingArchiveName() {
    return pollingArchiveName;
  }

  public void setPollingArchiveName(String pollingArchiveName) {
    this.pollingArchiveName = pollingArchiveName;
  }

  public DownloadPolling percent(Integer percent) {
    this.percent = percent;
    return this;
  }

   /**
   * Indicates archiving process completeness.
   * @return percent
  **/
  @Schema(example = "70", description = "Indicates archiving process completeness.")
  public Integer getPercent() {
    return percent;
  }

  public void setPercent(Integer percent) {
    this.percent = percent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DownloadPolling downloadPolling = (DownloadPolling) o;
    return Objects.equals(this.pollingArchiveName, downloadPolling.pollingArchiveName) &&
        Objects.equals(this.percent, downloadPolling.percent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pollingArchiveName, percent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DownloadPolling {\n");
    
    sb.append("    pollingArchiveName: ").append(toIndentedString(pollingArchiveName)).append("\n");
    sb.append("    percent: ").append(toIndentedString(percent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
