/*
 * ExaVault API
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.exavault.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.exavault.client.model.EmailList;
import com.exavault.client.model.User;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Response object for list of email lists
 */
@Schema(description = "Response object for list of email lists")

public class EmailListCollectionResponse {
  @SerializedName("responseStatus")
  private Integer responseStatus = null;

  @SerializedName("totalResults")
  private Integer totalResults = null;

  @SerializedName("returnedResults")
  private Integer returnedResults = null;

  @SerializedName("data")
  private List<EmailList> data = null;

  @SerializedName("included")
  private List<User> included = null;

  public EmailListCollectionResponse responseStatus(Integer responseStatus) {
    this.responseStatus = responseStatus;
    return this;
  }

   /**
   * Http status of response
   * @return responseStatus
  **/
  @Schema(description = "Http status of response")
  public Integer getResponseStatus() {
    return responseStatus;
  }

  public void setResponseStatus(Integer responseStatus) {
    this.responseStatus = responseStatus;
  }

  public EmailListCollectionResponse totalResults(Integer totalResults) {
    this.totalResults = totalResults;
    return this;
  }

   /**
   * Get totalResults
   * minimum: 0
   * @return totalResults
  **/
  @Schema(description = "")
  public Integer getTotalResults() {
    return totalResults;
  }

  public void setTotalResults(Integer totalResults) {
    this.totalResults = totalResults;
  }

  public EmailListCollectionResponse returnedResults(Integer returnedResults) {
    this.returnedResults = returnedResults;
    return this;
  }

   /**
   * Get returnedResults
   * minimum: 0
   * @return returnedResults
  **/
  @Schema(description = "")
  public Integer getReturnedResults() {
    return returnedResults;
  }

  public void setReturnedResults(Integer returnedResults) {
    this.returnedResults = returnedResults;
  }

  public EmailListCollectionResponse data(List<EmailList> data) {
    this.data = data;
    return this;
  }

  public EmailListCollectionResponse addDataItem(EmailList dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<EmailList>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @Schema(description = "")
  public List<EmailList> getData() {
    return data;
  }

  public void setData(List<EmailList> data) {
    this.data = data;
  }

  public EmailListCollectionResponse included(List<User> included) {
    this.included = included;
    return this;
  }

  public EmailListCollectionResponse addIncludedItem(User includedItem) {
    if (this.included == null) {
      this.included = new ArrayList<User>();
    }
    this.included.add(includedItem);
    return this;
  }

   /**
   * Get included
   * @return included
  **/
  @Schema(description = "")
  public List<User> getIncluded() {
    return included;
  }

  public void setIncluded(List<User> included) {
    this.included = included;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmailListCollectionResponse emailListCollectionResponse = (EmailListCollectionResponse) o;
    return Objects.equals(this.responseStatus, emailListCollectionResponse.responseStatus) &&
        Objects.equals(this.totalResults, emailListCollectionResponse.totalResults) &&
        Objects.equals(this.returnedResults, emailListCollectionResponse.returnedResults) &&
        Objects.equals(this.data, emailListCollectionResponse.data) &&
        Objects.equals(this.included, emailListCollectionResponse.included);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responseStatus, totalResults, returnedResults, data, included);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmailListCollectionResponse {\n");
    
    sb.append("    responseStatus: ").append(toIndentedString(responseStatus)).append("\n");
    sb.append("    totalResults: ").append(toIndentedString(totalResults)).append("\n");
    sb.append("    returnedResults: ").append(toIndentedString(returnedResults)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    included: ").append(toIndentedString(included)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
