/*
 * ExaVault API
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.exavault.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.exavault.client.model.FormAttributes;
import com.exavault.client.model.FormRelationships;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Regular form object.
 */
@Schema(description = "Regular form object.")

public class Form {
  @SerializedName("type")
  private String type = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("attributes")
  private FormAttributes attributes = null;

  @SerializedName("relationships")
  private FormRelationships relationships = null;

  public Form type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type is \&quot;form\&quot;.
   * @return type
  **/
  @Schema(example = "form", description = "Type is \"form\".")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Form id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * ID of the form.
   * @return id
  **/
  @Schema(example = "823752", description = "ID of the form.")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Form attributes(FormAttributes attributes) {
    this.attributes = attributes;
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @Schema(description = "")
  public FormAttributes getAttributes() {
    return attributes;
  }

  public void setAttributes(FormAttributes attributes) {
    this.attributes = attributes;
  }

  public Form relationships(FormRelationships relationships) {
    this.relationships = relationships;
    return this;
  }

   /**
   * Get relationships
   * @return relationships
  **/
  @Schema(description = "")
  public FormRelationships getRelationships() {
    return relationships;
  }

  public void setRelationships(FormRelationships relationships) {
    this.relationships = relationships;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Form form = (Form) o;
    return Objects.equals(this.type, form.type) &&
        Objects.equals(this.id, form.id) &&
        Objects.equals(this.attributes, form.attributes) &&
        Objects.equals(this.relationships, form.relationships);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, id, attributes, relationships);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Form {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    relationships: ").append(toIndentedString(relationships)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
