/*
 * ExaVault API
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.exavault.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.exavault.client.model.FormEntryAttributes;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Contains the data submitted for a form.
 */
@Schema(description = "Contains the data submitted for a form.")

public class FormEntry {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("attributes")
  private FormEntryAttributes attributes = null;

  public FormEntry id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Form entry id
   * @return id
  **/
  @Schema(example = "12345", description = "Form entry id")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public FormEntry type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type of item. \&quot;formEntry\&quot;
   * @return type
  **/
  @Schema(example = "formEntry", description = "Type of item. \"formEntry\"")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public FormEntry attributes(FormEntryAttributes attributes) {
    this.attributes = attributes;
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @Schema(description = "")
  public FormEntryAttributes getAttributes() {
    return attributes;
  }

  public void setAttributes(FormEntryAttributes attributes) {
    this.attributes = attributes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FormEntry formEntry = (FormEntry) o;
    return Objects.equals(this.id, formEntry.id) &&
        Objects.equals(this.type, formEntry.type) &&
        Objects.equals(this.attributes, formEntry.attributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, attributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FormEntry {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
