/*
 * ExaVault API
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.exavault.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.exavault.client.model.Resource;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Resource which was successfully copied or moved.
 */
@Schema(description = "Resource which was successfully copied or moved.")

public class ResourceCopyMove {
  @SerializedName("data")
  private Resource data = null;

  @SerializedName("meta")
  private Object meta = null;

  public ResourceCopyMove data(Resource data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @Schema(description = "")
  public Resource getData() {
    return data;
  }

  public void setData(Resource data) {
    this.data = data;
  }

  public ResourceCopyMove meta(Object meta) {
    this.meta = meta;
    return this;
  }

   /**
   * Meta object containing non-standard meta-information about the operation.
   * @return meta
  **/
  @Schema(example = "{\"id\":2321}", description = "Meta object containing non-standard meta-information about the operation.")
  public Object getMeta() {
    return meta;
  }

  public void setMeta(Object meta) {
    this.meta = meta;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceCopyMove resourceCopyMove = (ResourceCopyMove) o;
    return Objects.equals(this.data, resourceCopyMove.data) &&
        Objects.equals(this.meta, resourceCopyMove.meta);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, meta);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourceCopyMove {\n");
    
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
