/*
 * ExaVault API
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.exavault.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SessionActivityEntryAttributes
 */


public class SessionActivityEntryAttributes {
  @SerializedName("bytesTransferred")
  private Long bytesTransferred = null;

  @SerializedName("created")
  private String created = null;

  @SerializedName("duration")
  private Integer duration = null;

  @SerializedName("fileName")
  private String fileName = null;

  @SerializedName("fileSource")
  private String fileSource = null;

  @SerializedName("ipAddress")
  private String ipAddress = null;

  @SerializedName("operation")
  private String operation = null;

  @SerializedName("protocol")
  private String protocol = null;

  @SerializedName("sessionId")
  private String sessionId = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("username")
  private String username = null;

  public SessionActivityEntryAttributes bytesTransferred(Long bytesTransferred) {
    this.bytesTransferred = bytesTransferred;
    return this;
  }

   /**
   * Get bytesTransferred
   * @return bytesTransferred
  **/
  @Schema(example = "10815676", description = "")
  public Long getBytesTransferred() {
    return bytesTransferred;
  }

  public void setBytesTransferred(Long bytesTransferred) {
    this.bytesTransferred = bytesTransferred;
  }

  public SessionActivityEntryAttributes created(String created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @Schema(example = "2019-10-18T06:48:40Z", description = "")
  public String getCreated() {
    return created;
  }

  public void setCreated(String created) {
    this.created = created;
  }

  public SessionActivityEntryAttributes duration(Integer duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @Schema(example = "5", description = "")
  public Integer getDuration() {
    return duration;
  }

  public void setDuration(Integer duration) {
    this.duration = duration;
  }

  public SessionActivityEntryAttributes fileName(String fileName) {
    this.fileName = fileName;
    return this;
  }

   /**
   * Get fileName
   * @return fileName
  **/
  @Schema(example = "/test2/Cassandra2020The20Definitive20Guide.2030947496.pdf", description = "")
  public String getFileName() {
    return fileName;
  }

  public void setFileName(String fileName) {
    this.fileName = fileName;
  }

  public SessionActivityEntryAttributes fileSource(String fileSource) {
    this.fileSource = fileSource;
    return this;
  }

   /**
   * Get fileSource
   * @return fileSource
  **/
  @Schema(description = "")
  public String getFileSource() {
    return fileSource;
  }

  public void setFileSource(String fileSource) {
    this.fileSource = fileSource;
  }

  public SessionActivityEntryAttributes ipAddress(String ipAddress) {
    this.ipAddress = ipAddress;
    return this;
  }

   /**
   * Get ipAddress
   * @return ipAddress
  **/
  @Schema(example = "185.223.113.224", description = "")
  public String getIpAddress() {
    return ipAddress;
  }

  public void setIpAddress(String ipAddress) {
    this.ipAddress = ipAddress;
  }

  public SessionActivityEntryAttributes operation(String operation) {
    this.operation = operation;
    return this;
  }

   /**
   * Get operation
   * @return operation
  **/
  @Schema(example = "PASS", description = "")
  public String getOperation() {
    return operation;
  }

  public void setOperation(String operation) {
    this.operation = operation;
  }

  public SessionActivityEntryAttributes protocol(String protocol) {
    this.protocol = protocol;
    return this;
  }

   /**
   * Get protocol
   * @return protocol
  **/
  @Schema(example = "web", description = "")
  public String getProtocol() {
    return protocol;
  }

  public void setProtocol(String protocol) {
    this.protocol = protocol;
  }

  public SessionActivityEntryAttributes sessionId(String sessionId) {
    this.sessionId = sessionId;
    return this;
  }

   /**
   * Get sessionId
   * @return sessionId
  **/
  @Schema(example = "5da9b4a8bd961dfa0a56fa0dc15aaffe57069271b389e", description = "")
  public String getSessionId() {
    return sessionId;
  }

  public void setSessionId(String sessionId) {
    this.sessionId = sessionId;
  }

  public SessionActivityEntryAttributes status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(example = "-", description = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public SessionActivityEntryAttributes username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @Schema(example = "ykravchuk", description = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionActivityEntryAttributes sessionActivityEntryAttributes = (SessionActivityEntryAttributes) o;
    return Objects.equals(this.bytesTransferred, sessionActivityEntryAttributes.bytesTransferred) &&
        Objects.equals(this.created, sessionActivityEntryAttributes.created) &&
        Objects.equals(this.duration, sessionActivityEntryAttributes.duration) &&
        Objects.equals(this.fileName, sessionActivityEntryAttributes.fileName) &&
        Objects.equals(this.fileSource, sessionActivityEntryAttributes.fileSource) &&
        Objects.equals(this.ipAddress, sessionActivityEntryAttributes.ipAddress) &&
        Objects.equals(this.operation, sessionActivityEntryAttributes.operation) &&
        Objects.equals(this.protocol, sessionActivityEntryAttributes.protocol) &&
        Objects.equals(this.sessionId, sessionActivityEntryAttributes.sessionId) &&
        Objects.equals(this.status, sessionActivityEntryAttributes.status) &&
        Objects.equals(this.username, sessionActivityEntryAttributes.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bytesTransferred, created, duration, fileName, fileSource, ipAddress, operation, protocol, sessionId, status, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionActivityEntryAttributes {\n");
    
    sb.append("    bytesTransferred: ").append(toIndentedString(bytesTransferred)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    fileSource: ").append(toIndentedString(fileSource)).append("\n");
    sb.append("    ipAddress: ").append(toIndentedString(ipAddress)).append("\n");
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("    protocol: ").append(toIndentedString(protocol)).append("\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
