/*
 * ExaVault API
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.exavault.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.exavault.client.model.SSHKeyRelationshipsOwnerUser;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SSHKeyRelationships
 */


public class SSHKeyRelationships {
  @SerializedName("ownerUser")
  private SSHKeyRelationshipsOwnerUser ownerUser = null;

  public SSHKeyRelationships ownerUser(SSHKeyRelationshipsOwnerUser ownerUser) {
    this.ownerUser = ownerUser;
    return this;
  }

   /**
   * Get ownerUser
   * @return ownerUser
  **/
  @Schema(description = "")
  public SSHKeyRelationshipsOwnerUser getOwnerUser() {
    return ownerUser;
  }

  public void setOwnerUser(SSHKeyRelationshipsOwnerUser ownerUser) {
    this.ownerUser = ownerUser;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SSHKeyRelationships ssHKeyRelationships = (SSHKeyRelationships) o;
    return Objects.equals(this.ownerUser, ssHKeyRelationships.ownerUser);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ownerUser);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SSHKeyRelationships {\n");
    
    sb.append("    ownerUser: ").append(toIndentedString(ownerUser)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
