/*
 * ExaVault API
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.exavault.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.exavault.client.model.WebhookTriggers;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * UpdateWebhookRequestBody
 */


public class UpdateWebhookRequestBody {
  @SerializedName("endpointUrl")
  private String endpointUrl = null;

  @SerializedName("triggers")
  private WebhookTriggers triggers = null;

  @SerializedName("resource")
  private String resource = null;

  /**
   * Version of the webhooks message to send to the endpoint
   */
  @JsonAdapter(ResponseVersionEnum.Adapter.class)
  public enum ResponseVersionEnum {
    V2("v2"),
    V1("v1");

    private String value;

    ResponseVersionEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static ResponseVersionEnum fromValue(String text) {
      for (ResponseVersionEnum b : ResponseVersionEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<ResponseVersionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ResponseVersionEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ResponseVersionEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ResponseVersionEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("responseVersion")
  private ResponseVersionEnum responseVersion = null;

  public UpdateWebhookRequestBody endpointUrl(String endpointUrl) {
    this.endpointUrl = endpointUrl;
    return this;
  }

   /**
   * New endpoint URL to use for the webhook configuration
   * @return endpointUrl
  **/
  @Schema(example = "https://example.com/new-endpoint", description = "New endpoint URL to use for the webhook configuration")
  public String getEndpointUrl() {
    return endpointUrl;
  }

  public void setEndpointUrl(String endpointUrl) {
    this.endpointUrl = endpointUrl;
  }

  public UpdateWebhookRequestBody triggers(WebhookTriggers triggers) {
    this.triggers = triggers;
    return this;
  }

   /**
   * Get triggers
   * @return triggers
  **/
  @Schema(description = "")
  public WebhookTriggers getTriggers() {
    return triggers;
  }

  public void setTriggers(WebhookTriggers triggers) {
    this.triggers = triggers;
  }

  public UpdateWebhookRequestBody resource(String resource) {
    this.resource = resource;
    return this;
  }

   /**
   * Resource identifier of the top folder watched by this webhook.
   * @return resource
  **/
  @Schema(example = "/newfolder", description = "Resource identifier of the top folder watched by this webhook.")
  public String getResource() {
    return resource;
  }

  public void setResource(String resource) {
    this.resource = resource;
  }

  public UpdateWebhookRequestBody responseVersion(ResponseVersionEnum responseVersion) {
    this.responseVersion = responseVersion;
    return this;
  }

   /**
   * Version of the webhooks message to send to the endpoint
   * @return responseVersion
  **/
  @Schema(example = "v1", description = "Version of the webhooks message to send to the endpoint")
  public ResponseVersionEnum getResponseVersion() {
    return responseVersion;
  }

  public void setResponseVersion(ResponseVersionEnum responseVersion) {
    this.responseVersion = responseVersion;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateWebhookRequestBody updateWebhookRequestBody = (UpdateWebhookRequestBody) o;
    return Objects.equals(this.endpointUrl, updateWebhookRequestBody.endpointUrl) &&
        Objects.equals(this.triggers, updateWebhookRequestBody.triggers) &&
        Objects.equals(this.resource, updateWebhookRequestBody.resource) &&
        Objects.equals(this.responseVersion, updateWebhookRequestBody.responseVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endpointUrl, triggers, resource, responseVersion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateWebhookRequestBody {\n");
    
    sb.append("    endpointUrl: ").append(toIndentedString(endpointUrl)).append("\n");
    sb.append("    triggers: ").append(toIndentedString(triggers)).append("\n");
    sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
    sb.append("    responseVersion: ").append(toIndentedString(responseVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
