/*
 * ExaVault API
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.exavault.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * WebhookTriggersShares
 */


public class WebhookTriggersShares {
  @SerializedName("formSubmit")
  private Boolean formSubmit = null;

  public WebhookTriggersShares formSubmit(Boolean formSubmit) {
    this.formSubmit = formSubmit;
    return this;
  }

   /**
   * Send webhook messages when a receive folder form is submitted.
   * @return formSubmit
  **/
  @Schema(description = "Send webhook messages when a receive folder form is submitted.")
  public Boolean isFormSubmit() {
    return formSubmit;
  }

  public void setFormSubmit(Boolean formSubmit) {
    this.formSubmit = formSubmit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookTriggersShares webhookTriggersShares = (WebhookTriggersShares) o;
    return Objects.equals(this.formSubmit, webhookTriggersShares.formSubmit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(formSubmit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookTriggersShares {\n");
    
    sb.append("    formSubmit: ").append(toIndentedString(formSubmit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
