/*
 * ExaVault API
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.exavault.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.exavault.client.model.WebhookTriggersResources;
import com.exavault.client.model.WebhookTriggersShares;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * WebhookTriggers
 */


public class WebhookTriggers {
  @SerializedName("resources")
  private WebhookTriggersResources resources = null;

  @SerializedName("shares")
  private WebhookTriggersShares shares = null;

  public WebhookTriggers resources(WebhookTriggersResources resources) {
    this.resources = resources;
    return this;
  }

   /**
   * Get resources
   * @return resources
  **/
  @Schema(description = "")
  public WebhookTriggersResources getResources() {
    return resources;
  }

  public void setResources(WebhookTriggersResources resources) {
    this.resources = resources;
  }

  public WebhookTriggers shares(WebhookTriggersShares shares) {
    this.shares = shares;
    return this;
  }

   /**
   * Get shares
   * @return shares
  **/
  @Schema(description = "")
  public WebhookTriggersShares getShares() {
    return shares;
  }

  public void setShares(WebhookTriggersShares shares) {
    this.shares = shares;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookTriggers webhookTriggers = (WebhookTriggers) o;
    return Objects.equals(this.resources, webhookTriggers.resources) &&
        Objects.equals(this.shares, webhookTriggers.shares);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resources, shares);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookTriggers {\n");
    
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("    shares: ").append(toIndentedString(shares)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
